#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
board_budget.py - will this tree even import on that board, and roughly how
much heap will it take? No hardware, no CircuitPython: CPython's `ast`
plus mpy-cross.

    python tools/board_budget.py collector/hub_main.py node/node_lite.py node/node_full.py
    python tools/board_budget.py --board-toml path/to/circuitpython.toml node/node_lite.py
    MPY_CROSS=~/circuitpython/mpy-cross/build/mpy-cross python tools/board_budget.py ...

For each entry module it walks the import graph inside its tree and reports
every import of a CircuitPython built-in that the board does not have,
split into

  HARD   an unconditional module-level `import x` on the path from the
         entry: the module raises ImportError at load, nothing after it runs
  soft   inside a try/except that catches ImportError, under an `if`, or
         inside a function: the feature degrades or is skipped

Local modules reached only through such imports inherit that status. Third-party libraries (anything not local and not built-in) are
listed so you can check them against requirements-circup.txt.

The default board table is the one both Raspberry Pi Pico W zephyr-cp boards
generate (raspberrypi/rpi_pico_w_zephyr and rpi_pico2_w_zephyr,
tyeth/circuitpython @ 94bfd47b5f -- identical module lists). Pass
--board-toml with a board's autogenerated circuitpython.toml for any other.

Heap estimate: with mpy-cross available (MPY_CROSS or the usual build
paths) every reachable local .py is compiled and the .mpy sizes summed.
Measured on this project's modules, a loaded module holds about 1.2x its
.mpy size on a 32-bit build (2.0x on the 64-bit unix port), so the estimate
is sum(.mpy) x 1.2 for the local tree, plus the staged lib/*.mpy the entry
pulls in if a lib/ directory exists. It says nothing about runtime buffers
(sockets, TLS, display bitmaps) -- treat it as the floor.
"""

import ast
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Always present in every CircuitPython build (py/ core + shared extmod)
CORE = {
    "sys", "gc", "json", "struct", "time", "os", "errno", "collections",
    "io", "micropython", "array", "builtins", "math", "random", "re",
    "binascii", "select", "traceback", "__future__", "warnings",
}

# Both Pico W zephyr-cp boards @ 94bfd47b5f: [modules] entries that are true
PICO_ZEPHYR_TRUE = {
    "__future__", "_bleio", "adafruit_bus_device", "aesio", "bitmapfilter",
    "bitmaptools", "board", "busdisplay", "busio", "digitalio", "displayio",
    "epaperdisplay", "fontio", "fourwire", "framebufferio", "getpass",
    "gifio", "hashlib", "i2cdisplaybus", "ipaddress", "jpegio", "lvfontio",
    "math", "microcontroller", "msgpack", "nvm", "os", "rainbowio", "random",
    "rotaryio", "sdcardio", "sharpdisplay", "socketpool", "ssl", "storage",
    "struct", "supervisor", "terminalio", "tilepalettemapper", "time",
    "traceback", "usb_cdc", "usb_hid", "vectorio", "warnings", "wifi", "zlib",
    "asyncio", "binascii", "json", "re", "select",
}
# [modules] entries that are false on those boards (so: known CP module,
# absent here). Names never in the table at all (espnow, espidf) are
# "absent entirely" -- listed separately so nobody mistakes them for typos.
PICO_ZEPHYR_FALSE = {
    "_eve", "_pew", "_pixelmap", "_stage", "adafruit_pixelbuf", "alarm",
    "analogbufio", "analogio", "atexit", "audiobusio", "audiocore",
    "audiodelays", "audiofilewriter", "audiofilters", "audiofreeverb",
    "audioi2sin", "audioio", "audiomixer", "audiomp3", "audiopwmio",
    "audiospeed", "aurora_epaper", "bitbangio", "bitops", "camera", "canio",
    "codeop", "countio", "dotclockframebuffer", "dualbank", "emmcio",
    "floppyio", "frequencyio", "gnss", "hostnetwork", "i2cioexpander",
    "i2ctarget", "imagecapture", "is31fl3741", "keypad", "keypad_demux",
    "locale", "max3421e", "mcp4822", "mdns", "memorymap", "memorymonitor",
    "mipidsi", "neopixel_write", "onewireio", "paralleldisplaybus",
    "picogame", "ps2io", "pulseio", "pwmio", "qrio", "qspibus", "rclcpy",
    "rgbmatrix", "rtc", "sdioio", "spitarget", "synthio", "touchio", "uheap",
    "usb", "usb_audio", "usb_host", "usb_midi", "usb_video", "ustack",
    "watchdog", "zephyr_display", "zephyr_kernel",
}
# CircuitPython built-ins that exist on other ports and are simply not in
# the zephyr-cp table at all
NOT_IN_TABLE = {"espnow", "espidf", "socket", "_pixelmap", "ulab", "bitmaptools"}

MPY_RATIO_32 = 1.2
BUDGETS = {  # free RAM after the firmware's static use, from the .elf/.map
    "Pico W (RP2040)": 42292,
    "Pico 2 W (RP2350)": 303336,
}


def load_board_toml(path):
    true, false = set(), set()
    for line in open(path):
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(true|false)", line)
        if m:
            (true if m.group(2) == "true" else false).add(m.group(1))
    return true, false


class _Imports(ast.NodeVisitor):
    """Collect (module, kind, lineno). kind is how the import can fail:
    "hard"        module level, unconditional: ImportError at load
    "guarded"     inside a try whose handlers catch ImportError/everything
    "conditional" under an if/while at module level (e.g. `if caps.HAS_X:`)
    "deferred"    inside a function body: only when that function runs
    """

    def __init__(self):
        self.found = []
        self._guard = 0
        self._cond = 0
        self._func = 0

    def _catches_import_error(self, node):
        for h in node.handlers:
            if h.type is None:
                return True
            if isinstance(h.type, ast.Tuple):
                names = [getattr(e, "id", None) for e in h.type.elts]
            else:
                names = [getattr(h.type, "id", None)]
            if any(n in ("ImportError", "Exception", "BaseException")
                   for n in names):
                return True
        return False

    def visit_Try(self, node):
        g = self._catches_import_error(node)
        self._guard += g
        for n in node.body:
            self.visit(n)
        self._guard -= g
        for h in node.handlers:
            self.visit(h)
        for n in node.orelse + node.finalbody:
            self.visit(n)

    def _visit_cond(self, node):
        self._cond += 1
        self.generic_visit(node)
        self._cond -= 1

    visit_If = visit_While = visit_For = _visit_cond

    def _visit_func(self, node):
        self._func += 1
        self.generic_visit(node)
        self._func -= 1

    visit_FunctionDef = visit_AsyncFunctionDef = visit_Lambda = _visit_func

    def _kind(self):
        if self._guard:
            return "guarded"
        if self._func:
            return "deferred"
        if self._cond:
            return "conditional"
        return "hard"

    def visit_Import(self, node):
        for a in node.names:
            self.found.append((a.name.split(".")[0], self._kind(), node.lineno))

    def visit_ImportFrom(self, node):
        if node.module:
            self.found.append((node.module.split(".")[0], self._kind(), node.lineno))


def imports_of(path):
    tree = ast.parse(open(path, encoding="utf-8").read(), path)
    v = _Imports()
    v.visit(tree)
    return v.found


def walk(entry):
    """{module: (worst_kind, [(importer, lineno, kind)])} for every import
    reachable from entry inside its directory. A local module reached only
    through guarded/conditional/deferred imports inherits that kind."""
    tree_dir = os.path.dirname(os.path.abspath(entry))
    rank = {"hard": 0, "conditional": 1, "deferred": 2, "guarded": 3}
    seen = {}
    local = {}
    start = os.path.splitext(os.path.basename(entry))[0]
    local[start] = "hard"
    todo = [(start, "hard")]
    while todo:
        mod, path_kind = todo.pop()
        path = os.path.join(tree_dir, mod + ".py")
        if not os.path.exists(path):
            continue
        for name, kind, lineno in imports_of(path):
            k = kind if rank[kind] >= rank[path_kind] else path_kind
            rec = seen.setdefault(name, ["guarded", []])
            if rank[k] < rank[rec[0]]:
                rec[0] = k
            rec[1].append((mod, lineno, k))
            if os.path.exists(os.path.join(tree_dir, name + ".py")):
                if name not in local or rank[k] < rank[local[name]]:
                    local[name] = k
                    todo.append((name, k))
    return tree_dir, local, seen


def find_mpy_cross():
    cand = [os.environ.get("MPY_CROSS"), shutil.which("mpy-cross"),
            os.path.expanduser("~/circuitpython/mpy-cross/build/mpy-cross"),
            os.path.join(ROOT, "build", "mpy-cross", "mpy-cross")]
    for c in cand:
        if c and os.path.exists(c) and os.access(c, os.X_OK):
            return c
    return None


def mpy_size(mpy_cross, path):
    out = "/tmp/_bb_%s.mpy" % os.path.basename(path)
    r = subprocess.run([mpy_cross, "-o", out, path], capture_output=True, text=True)
    if r.returncode != 0:
        return None, r.stderr.strip()
    n = os.path.getsize(out)
    os.remove(out)
    return n, ""


def lib_size(tree_dir, name):
    """Bytes of staged lib/<name>(.mpy|/ *.mpy|*.py) if present."""
    lib = os.path.join(tree_dir, "lib")
    total = 0
    for cand in (os.path.join(lib, name + ".mpy"), os.path.join(lib, name + ".py")):
        if os.path.exists(cand):
            return os.path.getsize(cand)
    d = os.path.join(lib, name)
    if os.path.isdir(d):
        for dp, _, fs in os.walk(d):
            for f in fs:
                if f.endswith((".mpy", ".py")):
                    total += os.path.getsize(os.path.join(dp, f))
        return total
    return None


def report(entry, true, false, mpy_cross):
    tree_dir, local, seen = walk(entry)
    print("=" * 72)
    print(entry)
    hard, soft, libs = [], [], []
    for name, (worst, uses) in sorted(seen.items()):
        if name in local or name in CORE or name in true:
            continue
        if name in false or name in NOT_IN_TABLE:
            why = "absent from this port" if name in NOT_IN_TABLE else "disabled on this board"
            where = ", ".join("%s:%d%s" % (m, l, "" if k == "hard" else " (%s)" % k)
                              for m, l, k in uses)
            (hard if worst == "hard" else soft).append("%-16s %-26s %s" % (name, why, where))
        else:
            libs.append(name)
    print("  HARD (unconditional module-level import of a missing built-in -> ImportError at load):")
    for h in hard or ["    (none)"]:
        print("    " + h if not h.startswith("    ") else h)
    print("  soft (guarded / conditional / deferred; the feature degrades or is skipped):")
    for s_ in soft or ["    (none)"]:
        print("    " + s_ if not s_.startswith("    ") else s_)
    print("  libraries (must be in lib/, see requirements-circup.txt): %s" % ", ".join(sorted(libs)))
    print("  local modules reached: %s" % ", ".join(
        "%s%s" % (m, "" if k == "hard" else "*") for m, k in sorted(local.items()))
        + "   (* = only via a guarded/conditional/deferred import)")
    if mpy_cross:
        total = 0
        rows = []
        for m in sorted(local):
            n, err = mpy_size(mpy_cross, os.path.join(tree_dir, m + ".py"))
            if n is None:
                rows.append("    %-18s REJECTED: %s" % (m, err))
            else:
                total += n
                rows.append("    %-18s %6d B" % (m, n))
        print("  mpy-cross (%s):" % mpy_cross)
        for r in rows:
            print(r)
        est = int(total * MPY_RATIO_32)
        libtot = 0
        for l in libs:
            s = lib_size(tree_dir, l)
            if s:
                libtot += s
        print("    local .mpy total %d B -> ~%d B of heap when loaded (x%.1f)" % (total, est, MPY_RATIO_32))
        if libtot:
            print("    staged lib/ for those libraries: %d B -> ~%d B more" % (libtot, int(libtot * MPY_RATIO_32)))
        floor = est + int(libtot * MPY_RATIO_32)
        for board, budget in BUDGETS.items():
            print("    %-18s budget %6d B: %s (%d B left before any runtime data)"
                  % (board, budget, "fits" if floor < budget else "DOES NOT FIT", budget - floor))
    return hard


def main():
    args = sys.argv[1:]
    true, false = PICO_ZEPHYR_TRUE, PICO_ZEPHYR_FALSE
    if "--board-toml" in args:
        i = args.index("--board-toml")
        true, false = load_board_toml(args[i + 1])
        del args[i:i + 2]
    # defaults: what is meant to load on the Pico boards. node_full is the
    # ESP32 node (espnow + alarm) and fails here by design -- pass it
    # explicitly to see exactly which imports would stop it.
    entries = args or ["collector/hub_main.py", "node/node_lite.py"]
    mpy_cross = find_mpy_cross()
    if not mpy_cross:
        print("(no mpy-cross found: set MPY_CROSS for size estimates)")
    hard_total = 0
    for e in entries:
        hard_total += len(report(os.path.join(ROOT, e) if not os.path.isabs(e) else e, true, false, mpy_cross))
    print("=" * 72)
    print("%d hard failure(s)" % hard_total)
    sys.exit(1 if hard_total else 0)


if __name__ == "__main__":
    main()
